### ISSUE TITLE
Divide construction of SMILES and SMILES file reading

### ISSUE THREAD

**Issue by tagirshin** [cimm-kzn/CGRtools#160]
Is it possible to divide SMILESRead in two functions, one for reading SMILES file and convertion from SMILES to graph? Since graph has it is own function to convert into SMILES `str(graph) -> SMILES`, it could be more practical to have inverse function like `to_graph(SMILES) -> graph`. However now you should always import StringIO and write something like this:

`with StringIO(smi) as f, SMILESRead(f) as m:` 
&nbsp;&nbsp;&nbsp;&nbsp;`mol = next(m)`

**Comment by stsouko** [comment]
```
smiles = SMILESRead.create_parser(ignore_stereo=False, remap=False, ignore=True)
drink = smiles('CCO')
```

**Comment by tagirshin** [comment]
Well okay, it is better than before, thanks! 

And also, with `CCO` it is better not to forget drink `O` 😄
