### ISSUE TITLE
t_decomposed = preparer.decompose(rc.compose())

### ISSUE THREAD

**Issue by fengjiaxin** [cimm-kzn/CGRtools#35]
how to generate ReactionContainer object?
I found the reactions.dat file is supplied,but i want to construct ReactionContainer by myself
the code are:

from CGRtools import CGRpreparer # import of CGRpreparer
from CGRtools.containers import ReactionContainer,MoleculeContainer
from CGRtools.utils.rdkit import from_rdkit_molecule
from rdkit import Chem

def MoleculeContainer_from_smiles(smiles):
    m = Chem.MolFromSmiles(smiles)
    return from_rdkit_molecule(m)

r1 = MoleculeContainer_from_smiles(r1_smiles)
r2 = MoleculeContainer_from_smiles(r2_smiles)
r3 = MoleculeContainer_from_smiles(r3_smiles)
p1 = MoleculeContainer_from_smiles(p1_smiles)

rc = ReactionContainer(reactants=[r1,r2,r3], products=[p1])
type(rc)

preparer = CGRpreparer()
t_decomposed = preparer.decompose(rc.compose())

and i found errors as follow:
KeyError                                  Traceback (most recent call last)
~/fengjiaxin/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/CGRtools/cache.py in wrapper(self)
     46         try:
---> 47             return self.__dict__[name]
     48         except KeyError:

KeyError: '_cached_method_compose'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-28-cbec654ad72d> in <module>
      1 preparer = CGRpreparer()
----> 2 t_decomposed = preparer.decompose(rc.compose())

~/fengjiaxin/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/CGRtools/cache.py in wrapper(self)
     47             return self.__dict__[name]
     48         except KeyError:
---> 49             value = self.__dict__[name] = func(self)
     50             return value
     51     return wrapper

~/fengjiaxin/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/CGRtools/containers/reaction.py in compose(self)
    227             if not all(isinstance(x, (MoleculeContainer, CGRContainer)) for x in rr):
    228                 raise TypeError('Queries not composable')
--> 229             r = reduce(or_, rr)
    230         else:
    231             r = MoleculeContainer()

~/fengjiaxin/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/CGRtools/algorithms/union.py in __or__(self, other)
     24         G | H is union of graphs
     25         """
---> 26         return self.union(other)
     27 
     28     def union(self, other):

~/fengjiaxin/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/CGRtools/algorithms/union.py in union(self, other)
     30             raise TypeError('BaseContainer subclass expected')
     31         if self._node.keys() & set(other):
---> 32             raise KeyError('mapping of graphs is not disjoint')
     33 
     34         # dynamic container resolving

KeyError: 'mapping of graphs is not disjoint'

am i  wrong with construct the ReactionContainer
if i was wrong,can you supply the right code to construct the ReactionContainer
Thanks very much

**Comment by stsouko** [comment]
Hello!
You try to construct CGR.
The reaction container (rc) you have obtained is valid.
However, for CGR you need correct atom-to-atom mapping in ReactionContainer.
molecules r1, r2, r3 have intersect of atom numbers.

Please describe the purpose of following operation:
`t_decomposed = preparer.decompose(rc.compose())`

**Comment by fengjiaxin** [comment]
hi:
now i have the atom to atom reaction smiles,but still get errors:
and i found the tutorals and get no relation information, 
#[CH3:1][CH2:2]O.[OH:4][C:5]([C:7](=[O:9])[OH:8])=[O:6].[CH3:10][CH2:11][O-]>>[CH3:10][CH2:11][O:6][C:5]([C:7]([O:8][CH2:1][CH3:2])=[O:9])=[O:4]
r1_smiles = '[CH3:1][CH2:2]O[OH:4][C:5]([C:7](=[O:9])[OH:8])=[O:6]'
r2_smiles = '[OH:4][C:5]([C:7](=[O:9])[OH:8])=[O:6]'
r3_smiles = '[CH3:10][CH2:11][O-]'
p1_smiles = '[CH3:10][CH2:11][O:6][C:5]([C:7]([O:8][CH2:1][CH3:2])=[O:9])=[O:4]'
rc = ReactionContainer(reactants=[r1,r2,r3], products=[p1])

preparer = CGRpreparer()
t_decomposed = preparer.decompose(rc.compose())

and get errors:KeyError: 'mapping of graphs is not disjoint'
now i have the atom 2 atom reaction and how to generate ReactionContainer?
thanks

**Comment by stsouko** [comment]
You can to use
```
from CGRtools.files import SMILESread
from io import StringIO

rc = next(SMILESread(StringIO('SMILES string of reaction')))
```

or if need:

```
r1_smiles = next(SMILESread(StringIO('[CH3:1][CH2:2]O[OH:4]C:5=[O:6]')))
r2_smiles = next(SMILESread(StringIO('[OH:4]C:5=[O:6]')))
r3_smiles = next(SMILESread(StringIO('[CH3:10][CH2:11][O-]')))
p1_smiles = next(SMILESread(StringIO('[CH3:10][CH2:11][O:6]C:5=[O:4]')))
rc = ReactionContainer(reactants=[r1,r2,r3], products=[p1])
```

Note: Your SMILES invalid `[CH3:1][CH2:2]O.[OH:4]C:5=[O:6].[CH3:10][CH2:11][O-]>>[CH3:10][CH2:11][O:6]C:5=[O:4]`

**Comment by fengjiaxin** [comment]
thanks a lot , i solve the problem
