### ISSUE TITLE
it would be nice a CGR_from_reaction method

### ISSUE THREAD

**Issue by UnixJunkie** [cimm-kzn/CGRtools#4]
currently, you need to use the tilde operator, but this is not very easy to find / explicit
when you are new to this package.
Also, there could be a to_CGR method in the reaction object/container.

**Comment by tagirshin** [comment]
Hello, this method exists in ReactionContainer and known as `compose`. So, instead of using tilde, you can obtain a CGR by  `ReactionContainer.compose()`.

**Comment by UnixJunkie** [comment]
Thanks a lot, since I prefer human-readable code to overloaded operators.
