### ISSUE TITLE
Bug in Reactor (delete atoms)

### ISSUE THREAD

**Issue by HighHumidity** [cimm-kzn/CGRtools#62]
Initial reaction:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/54441995/67020420-dbb9de80-f106-11e9-8dee-55d6d652a6b3.png">

Extracted template:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/54441995/67020457-ed02eb00-f106-11e9-9a93-ab9af48b26bd.png">

Created reaction:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/54441995/67020536-05730580-f107-11e9-835f-c9a60d6ebad1.png">

The sodium ion erroneously appeared in the products.

**Comment by stsouko** [comment]
not a bug
