### ISSUE TITLE
IDname of molecules 

### ISSUE THREAD

**Issue by Okonce** [cimm-kzn/CGRtools#65]
Проще показать, что хочу. Хочу чтобы была ID-шка молекулы

ethanol

  9  8  0  0  0  0            999 V2000
   -1.4732   -4.4786    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7587   -4.0661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0443   -4.4786    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8857   -3.7641    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1877   -4.8911    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0607   -5.1930    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1461   -3.3376    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3714   -3.3376    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0443   -5.3036    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  1  6  1  0  0  0  0
  2  7  1  0  0  0  0
  2  8  1  0  0  0  0
  3  9  1  0  0  0  0
M  END
$$$$

**Comment by stsouko** [comment]
done
