### ISSUE TITLE
XYZ parser

### ISSUE THREAD

**Issue by TimurGimadiev** [cimm-kzn/CGRtools#78]
Add XYZ parser and may be some intermediate parser like one that can work with JSON or dictionary representation, for the case of self-made parsers: 
my awesome parser(make dict or JSON) --> intermediate parser(parse redefined fields or I give correspondence of each filed teach in some dict) --> CGR objects

**Comment by stsouko** [comment]
started: https://github.com/cimm-kzn/CGRtools/commit/6e9cde70cc66d678b45fd7715743f8bd8e5654b7

**Comment by stsouko** [comment]
tests need
