### ISSUE TITLE
Converting SMILES string into molecule container

### ISSUE THREAD

**Issue by AsyaOrlova** [cimm-kzn/CGRtools#8]
Hello! I wonder if it is possible to convert individual SMILES string into a molecule container object? Without working with files

**Comment by Academich** [comment]
Seems like it's not supported, but there is a hack. You can create a parser instance with a placeholder StringIO object and use its `parse` method. It can parse a SMILES string of either a molecule or a reaction and return a new MoleculeContainer or ReactionContainer respectively.  

```Python
from io import StringIO
from CGRtools.files import SMILESRead

parser = SMILESRead(StringIO())
smiles = "CCN"
container = parser.parse(smiles)  # type(container) is CGRtools.containers.molecule.MoleculeContainer
parser.close(force=True) # Don't forget to close the placeholder StringIO object when the parser is no longer needed
```

**Comment by tmadzhidov** [comment]
There is embedded `smiles` method.

It works as follows:

`from CGRtools import smiles`
`m=smiles('CCC')`
`m.clean2d() #for visualization`
`m`
