### ISSUE TITLE
1. data types notebook: m7.substructure([4, 5, 6, 7, 8, 9], as_view=False) error

### ISSUE THREAD

**Issue by joergkurtwegner** [cimm-kzn/CGRtools#80]
data types notebook: m7.substructure([4, 5, 6, 7, 8, 9], as_view=False)
breaks with
TypeError: substructure() got an unexpected keyword argument 'as_view'

Fresh Python3.7 PIP install with code from today.

**Comment by stsouko** [comment]
Tutorial tested on CGRtools v3.1. We plan to update it to master version soon.
